name: docker deployment
on: workflow_dispatch
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker image build
        run: docker build -t ${{vars.DOCKER_USERNAME}}/food-app:latest .
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: push latest image to docker hub
        run: docker push ${{vars.DOCKER_USERNAME}}/food-app:latest
  old-deployment:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove Container
        run: docker container rm -f food-app
  deploy:
    needs: old-deployment
    runs-on: self-hosted
    steps:
      - name: pull the image
        run: docker pull ${{vars.DOCKER_USERNAME}}/food-app
      - name: run the container
        run: docker container run -dt --name food-prod -p 8085:80 ${{vars.DOCKER_USERNAME}}/food-app
      - name: container status
        run: docker container ps -a




    
